# Autograd

Supposing function was determined by $y = 2 x^T x$, we want to make gradiation from column vector

In [9]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

Before calculation of gradient of $y$ about $x$, we need memory to store it.

In [10]:
x.requires_grad_(True) # equvient to x = torch.arange(4.0, requires_grad=True)
x.grad # default value: None

Now, let's compute $y$

In [11]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)


The gradient of $y$ with respect to each component of $x$ is automatically computed by invoking the backpropagation function.

In [12]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [13]:
x.grad == 4 * x

tensor([True, True, True, True])

Let's compute another function respect to $x$

In [14]:
# By default, PyTorch accumulates gradients. We need to clear the previous values.
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In deep learning, our goal is not to compute the differential matrix, but rather the sum of the partial derivatives computed separately for each sample in the batch.

In [15]:
x.grad.zero_()
y = x * x
# equvalent to y.backward(torch.ones(len(x)))
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

Move certain computations outside of the recorded computational graph.

In [17]:
x.grad.zero_()
y = x * x
# u = y.detach()
u = y
z = u * x

z.sum().backward()
# x.grad == u
x.grad == 3 * x ** 2

tensor([True, True, True, True])

In [21]:
def f(a):
  b = a * 2
  while b.norm() < 1000:
    b = b * 2
  if b.sum() > 0:
    c = b
  else:
    c = 100 * b
  return c

a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()

a.grad == d / a

tensor(True)