# Data Operation

In this chapter, you will study how to use `torch` simply.
- 1. how to create a tensor?
- 2. how to change the shape of a tensor?
- 3. how to operate among tensors with standard operator such as `+`, `-`, `*`, `/` and `**`?
- 4.

Firstly, we should load the `pytorch` package. You need to be careful that the `pytorch` package load in python is `torch`.

In [1]:
import torch

**Tensor**: an array composed by number with multiple dimension

In [2]:
x = torch.arange(12) # x is 1-D vector
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
x.shape, x.numel()

torch.Size([12])

We can use `reshape` function to change the shape of the tensor without change elements

In [9]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [10]:
X.shape, X.numel()

torch.Size([3, 4])

We can also create some special distribution tensor

- `zeros()`: all elements are `0`.
- `ones()`: all elements are `1`.
- `random.rand()`: all elements valued by random number.(need to import `random` package)

In [12]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

Tensor also could be created by python list with number type

In [15]:
torch.tensor([
    [2, 1, 4, 3],
    [6, 6, 6, 6],
    [9, 19, 2, 1]]
)

tensor([[ 2,  1,  4,  3],
        [ 6,  6,  6,  6],
        [ 9, 19,  2,  1]])

## Basic Operation

If you use basic operator `+`, `-`, `*`, `/`, `**` to operate within tensor, the result will be returned by operating with corresponding elements in tensor

In [16]:
x = torch.tensor([1, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])

x + y, x - y, x * y, x / y, x ** y

(tensor([ 3,  4,  6, 10]),
 tensor([-1,  0,  2,  6]),
 tensor([ 2,  4,  8, 16]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1,  4, 16, 64]))

Also, you can use the built-in math function in torch to operate.

In [17]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [20]:
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
Y = torch.tensor([
    [2, 1, 4, 3],
    [6, 6, 6, 6],
    [9, 19, 2, 1]
])

X.shape, Y.shape, torch.cat((X, Y), dim = 0), torch.cat((X, Y), dim = 1), torch.cat((X, Y), dim = 0).shape, torch.cat((X, Y), dim = 1).shape

(torch.Size([3, 4]),
 torch.Size([3, 4]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 6.,  6.,  6.,  6.],
         [ 9., 19.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  6.,  6.,  6.,  6.],
         [ 8.,  9., 10., 11.,  9., 19.,  2.,  1.]]),
 torch.Size([6, 4]),
 torch.Size([3, 8]))

Use logic operator `==` to construct logical tensor

In [21]:
X == Y

tensor([[False,  True, False,  True],
        [False, False,  True, False],
        [False, False, False, False]])

Sum: you will return tensor with only one elements by computing the sum of all elements in the tensor.

In [22]:
X.sum()

tensor(66.)

Despite the different shape, we can use **broadcasting mechanism** to operate tensor by element.

**broadcasting mechanism**:


In [24]:
a = torch.arange(3).reshape(3, 1)
b = torch.arange(2).reshape(1, 2)

a, b, a + b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]),
 tensor([[0, 1],
         [1, 2],
         [2, 3]]))

Besides reading, you can modify element by indexing or sliding

In [25]:
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [26]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

Allocating new memory by some operation.

In [27]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [29]:
Z = torch.zeros_like(Y)
print(f"id(Z): {id(Z)}")
Z[:] = X + Y
print(f"id(Z): {id(Z)}")

id(Z): 132779802682256
id(Z): 132779802682256


Tips: If you do not reuse the variable, we can also use `X[:] = X + Y` or `X += Y` to reduce memory store.

In [30]:
before = id(X)
x += Y
id(X) == before

RuntimeError: output with shape [4] doesn't match the broadcast shape [3, 4]

Numpy transition

In [31]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

1-D tensor transit to python scalar

In [32]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)