In [1]:
import torch

x = torch.tensor([3.0])
y = torch.tensor([2.0])

x + y, x * y, x / y, x ** y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [ ]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [ ]:
x[3], x[0:3]

(tensor(3), tensor([0, 1, 2]))

In [ ]:
len(x), x.shape

(4, torch.Size([4]))

In [ ]:
A = torch.arange(20).reshape(5, 4)
A, A.T

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([[ 0,  4,  8, 12, 16],
         [ 1,  5,  9, 13, 17],
         [ 2,  6, 10, 14, 18],
         [ 3,  7, 11, 15, 19]]))

In [ ]:
B = torch.tensor([
    [1, 2, 3],
    [2, 0, 4],
    [3, 4, 5]
])
B, B==B.T

(tensor([[1, 2, 3],
         [2, 0, 4],
         [3, 4, 5]]),
 tensor([[True, True, True],
         [True, True, True],
         [True, True, True]]))

A vector is a generalization of a scalar, and a matrix is a generalization of a vector.

In [2]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

Two tensors of the same shape will always produce a tensor of the same shape when any element-wise operation is applied.

In [3]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone() # allocate the new memory to store variable B
id(B) == id(A), A, A + B

(False,
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

## Hadamard Product of Two Matrices

The element-wise multiplication of two matrices is called the **Hadamard Product**, also known as the **element-wise product** or **pointwise product**. The Hadamard Product is computed by multiplying the corresponding elements of two matrices to produce a new matrix of the same shape.

### Definition
Given two matrices **A** and **B** of the same shape (m×n), their Hadamard Product **C** is also an m×n matrix, where each element \( c_{ij} \) is the product of the corresponding elements \( a_{ij} \) and \( b_{ij} \):

\[ C = A \circ B \]
\[ c_{ij} = a_{ij} \cdot b_{ij} \]

### Example
Suppose we have two 2×2 matrices **A** and **B**:

\[ A = \begin{pmatrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{pmatrix} \]
\[ B = \begin{pmatrix} b_{11} & b_{12} \\ b_{21} & b_{22} \end{pmatrix} \]

Their Hadamard Product **C** is:

\[ C = \begin{pmatrix} a_{11} \cdot b_{11} & a_{12} \cdot b_{12} \\ a_{21} \cdot b_{21} & a_{22} \cdot b_{22} \end{pmatrix} \]

### Applications
The Hadamard Product is widely used in various fields, including mathematics, engineering, image processing, and machine learning.

In [4]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [5]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

Use `sum()` function to compute the sum the all elements in the matrix

In [6]:
X = torch.arange(10).reshape(2, 5)
X.sum()

tensor(45)

Additionally, we can use `axis=` to indicate the sum of given axis.

In [8]:
X_sum_axis0 = X.sum(axis=0)
X_sum_axis1 = X.sum(axis=1)
X, X_sum_axis0, X_sum_axis1, X.shape, X_sum_axis0.shape, X_sum_axis1.shape

(tensor([[0, 1, 2, 3, 4],
         [5, 6, 7, 8, 9]]),
 tensor([ 5,  7,  9, 11, 13]),
 tensor([10, 35]),
 torch.Size([2, 5]),
 torch.Size([5]),
 torch.Size([2]))

In [9]:
X_sum = X.sum(axis=[0, 1]) # same as .sum()
X_sum

tensor(45)

The same effects is done with `.mean()`

In [14]:
X = torch.arange(10, dtype=torch.float32).reshape(2, 5)
X, X.mean(), X.mean(axis=0), X.mean(axis=1)

(tensor([[0., 1., 2., 3., 4.],
         [5., 6., 7., 8., 9.]]),
 tensor(4.5000),
 tensor([2.5000, 3.5000, 4.5000, 5.5000, 6.5000]),
 tensor([2., 7.]))

In [17]:
A.mean() == A.sum() / A.numel(), A.mean(axis=0) == A.sum(axis=0) / A.shape[0], A.mean(axis=1) == A.sum(axis=1) / A.shape[1]

(tensor(True),
 tensor([True, True, True, True]),
 tensor([True, True, True, True, True]))

In the example above, the dimension will be lost when performing the summation. Of course, it is also possible to keep the axis unchanged when calculating the total sum or the mean with parameter `keepdim=True`.

In [19]:
sum_X = X.sum(axis=1, keepdim=True)
X, sum_X, X / sum_X # boardcasting mechanism was performed by the same dimension with the two matrix.

(tensor([[0., 1., 2., 3., 4.],
         [5., 6., 7., 8., 9.]]),
 tensor([[10.],
         [35.]]),
 tensor([[0.0000, 0.1000, 0.2000, 0.3000, 0.4000],
         [0.1429, 0.1714, 0.2000, 0.2286, 0.2571]]))

Cumulative Sum: `cumsum()`

In [23]:
X = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)

cum_sum_X_dim0 = X.cumsum(dim=0)

cum_sum_X_dim1 = X.cumsum(dim=1)

print("Original Tensor X:")
print(X)
print("\nCumulative Sum along dim=0 (columns):")
print(cum_sum_X_dim0)
print("\nCumulative Sum along dim=1 (rows):")
print(cum_sum_X_dim1)

Original Tensor X:
tensor([[1., 2., 3.],
        [4., 5., 6.]])

Cumulative Sum along dim=0 (columns):
tensor([[1., 2., 3.],
        [5., 7., 9.]])

Cumulative Sum along dim=1 (rows):
tensor([[ 1.,  3.,  6.],
        [ 4.,  9., 15.]])


Dot product: The **dot product**, also known as the **scalar product** or **inner product**, is an operation between two vectors that results in a scalar value.
Matrice product: The

In [40]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
y = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
z = torch.tensor([[1,2], [3,4], [5,6]], dtype=torch.float32)
x, y, x.shape, y.shape, torch.mul(x, y), torch.matmul(x, z), torch.mm(x, z) # mul为点积， mm,matmul为矩阵乘法

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 torch.Size([2, 3]),
 torch.Size([2, 3]),
 tensor([[ 1.,  4.,  9.],
         [16., 25., 36.]]),
 tensor([[22., 28.],
         [49., 64.]]),
 tensor([[22., 28.],
         [49., 64.]]))

In [44]:
u = torch.tensor([3.0, -4.0])
torch.norm(u), torch.abs(u).sum(), torch.norm(torch.ones(4, 9))

(tensor(5.), tensor(7.), tensor(6.))